# variables <- colnames(input$data)
library(shiny)
library(shinythemes)
library(plotly)
library(doBy)
library(reshape)
library(plotrix)
library(corrplot)
library(tidyverse)
library('reshape2')
library("FactoMineR")
library("devtools")
library("factoextra")
library("missMDA")
library("dplyr")
